import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

/**
 * Event entity which is used to store event information in database.
 */
@Entity()
export class EventEntity {
  /**
   * Event ID. Generated by database.
   */
  @PrimaryGeneratedColumn()
  id: string;

  /**
   * Event title. Required.
   */
  @Column()
  title: string;

  /**
   * Event description. Optional.
   */
  @Column({ nullable: true })
  desc: string;

  /**
   * Event start time. Required.
   */
  @Column()
  start_time: Date;

  /**
   * Event end time. Required.
   */
  @Column()
  end_time: Date;

  /**
   * Event location. Optional.
   */
  @Column({ nullable: true })
  location: string;
}
