import {
  Column,
  Entity,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { UserEntity } from 'src/users/models/user.entity';
import { ClientEntity } from 'src/users/models/client.entity';

/**
 * Event entity which is used to store event information in database.
 */
@Entity()
export class EventEntity {
  /**
   * Event ID. Generated by database.
   */
  @PrimaryGeneratedColumn()
  eid: string;

  @ManyToOne(() => ClientEntity)
  @JoinColumn({ name: 'cid' })
  client: ClientEntity;

  /**
   * Event title. Required.
   */
  @Column()
  title: string;

  /**
   * Event description. Optional.
   */
  @Column({ nullable: true })
  desc: string;

  /**
   * Event start time. Required.
   */
  @Column()
  start_time: Date;

  /**
   * Event end time. Required.
   */
  @Column()
  end_time: Date;

  /**
   * Event location. Optional.
   */
  @Column({ nullable: true })
  location: string;

  // @Column({ nullable: true })
  // host: string;  // todo: change to user entity

  /**
   * Event host. Required.
   */
  @Column()
  host: string;
}
