name: CI

on: [push, pull_request]

jobs:
  build-and-deploy:
    # This job runs on a Linux instance
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        # Sets up Docker Buildx to provide Docker's build capabilities
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        # Caches Docker layers to speed up subsequent builds
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and Start Service
        # Runs Docker Compose to build and start your service
        run: sudo docker-compose up --build

      - name: Static Code Analysis
        run: pnpm lint

      - name: Run e2e Tests
        run: pnpm test:e2e

      - name: Run init Tests
        run: pnpm test

      - name: Run Tests and Generate Coverage Report
        run: pnpm test:cov

      - name: Generate documentation
        run: pnpm compodoc
